logging:
  level:
    com.verygoodsecurity: debug
    org.springframework.web: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

marqeta:
  api-keys:
    application-token: ${MARQETA_APPLICATION_TOKEN}
    master-access-token: ${MARQETA_MASTER_ACCESS_TOKEN}
  card-product:
    token: ${MARQETA_CARD_PRODUCT_TOKEN:6454fc38-6146-4eb3-89a2-5286431ef3ad}

vgs:
  proxy:
    url: ${VGS_PROXY_URL}
